// Code generated by entc, DO NOT EDIT.

package order

import (
	"time"
)

const (
	// Label holds the string label denoting the order type in the database.
	Label = "order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOid holds the string denoting the oid field in the database.
	FieldOid = "oid"
	// FieldOrderer holds the string denoting the orderer field in the database.
	FieldOrderer = "orderer"
	// FieldReceiver holds the string denoting the receiver field in the database.
	FieldReceiver = "receiver"
	// FieldDrugName holds the string denoting the drug_name field in the database.
	FieldDrugName = "drug_name"
	// FieldDrugStandard holds the string denoting the drug_standard field in the database.
	FieldDrugStandard = "drug_standard"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldRegisterName holds the string denoting the register_name field in the database.
	FieldRegisterName = "register_name"
	// FieldStorageCondition holds the string denoting the storage_condition field in the database.
	FieldStorageCondition = "storage_condition"
	// FieldDeliveryDriverName holds the string denoting the delivery_driver_name field in the database.
	FieldDeliveryDriverName = "delivery_driver_name"
	// FieldDeliveryDriverTelNo holds the string denoting the delivery_driver_tel_no field in the database.
	FieldDeliveryDriverTelNo = "delivery_driver_tel_no"
	// FieldMemo holds the string denoting the memo field in the database.
	FieldMemo = "memo"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeManager holds the string denoting the manager edge name in mutations.
	EdgeManager = "manager"
	// Table holds the table name of the order in the database.
	Table = "orders"
	// ManagerTable is the table that holds the manager relation/edge.
	ManagerTable = "orders"
	// ManagerInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	ManagerInverseTable = "accounts"
	// ManagerColumn is the table column denoting the manager relation/edge.
	ManagerColumn = "account_orders"
)

// Columns holds all SQL columns for order fields.
var Columns = []string{
	FieldID,
	FieldOid,
	FieldOrderer,
	FieldReceiver,
	FieldDrugName,
	FieldDrugStandard,
	FieldQuantity,
	FieldRegisterName,
	FieldStorageCondition,
	FieldDeliveryDriverName,
	FieldDeliveryDriverTelNo,
	FieldMemo,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "orders"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"account_orders",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultOid holds the default value on creation for the "oid" field.
	DefaultOid string
	// OrdererValidator is a validator for the "orderer" field. It is called by the builders before save.
	OrdererValidator func(string) error
	// ReceiverValidator is a validator for the "receiver" field. It is called by the builders before save.
	ReceiverValidator func(string) error
	// DrugNameValidator is a validator for the "drug_name" field. It is called by the builders before save.
	DrugNameValidator func(string) error
	// DrugStandardValidator is a validator for the "drug_standard" field. It is called by the builders before save.
	DrugStandardValidator func(string) error
	// StorageConditionValidator is a validator for the "storage_condition" field. It is called by the builders before save.
	StorageConditionValidator func(string) error
	// DefaultDeliveryDriverName holds the default value on creation for the "delivery_driver_name" field.
	DefaultDeliveryDriverName string
	// DeliveryDriverNameValidator is a validator for the "delivery_driver_name" field. It is called by the builders before save.
	DeliveryDriverNameValidator func(string) error
	// DefaultDeliveryDriverTelNo holds the default value on creation for the "delivery_driver_tel_no" field.
	DefaultDeliveryDriverTelNo string
	// DeliveryDriverTelNoValidator is a validator for the "delivery_driver_tel_no" field. It is called by the builders before save.
	DeliveryDriverTelNoValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updatedAt" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
)
