// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ChainExpressbill/coldchain/ent/account"
	"github.com/ChainExpressbill/coldchain/ent/order"
	"github.com/google/uuid"
)

// OrderCreate is the builder for creating a Order entity.
type OrderCreate struct {
	config
	mutation *OrderMutation
	hooks    []Hook
}

// SetOid sets the "oid" field.
func (oc *OrderCreate) SetOid(u uuid.UUID) *OrderCreate {
	oc.mutation.SetOid(u)
	return oc
}

// SetNillableOid sets the "oid" field if the given value is not nil.
func (oc *OrderCreate) SetNillableOid(u *uuid.UUID) *OrderCreate {
	if u != nil {
		oc.SetOid(*u)
	}
	return oc
}

// SetOrderer sets the "orderer" field.
func (oc *OrderCreate) SetOrderer(s string) *OrderCreate {
	oc.mutation.SetOrderer(s)
	return oc
}

// SetReceiver sets the "receiver" field.
func (oc *OrderCreate) SetReceiver(s string) *OrderCreate {
	oc.mutation.SetReceiver(s)
	return oc
}

// SetDrugName sets the "drug_name" field.
func (oc *OrderCreate) SetDrugName(s string) *OrderCreate {
	oc.mutation.SetDrugName(s)
	return oc
}

// SetDrugStandard sets the "drug_standard" field.
func (oc *OrderCreate) SetDrugStandard(s string) *OrderCreate {
	oc.mutation.SetDrugStandard(s)
	return oc
}

// SetQuantity sets the "quantity" field.
func (oc *OrderCreate) SetQuantity(i int) *OrderCreate {
	oc.mutation.SetQuantity(i)
	return oc
}

// SetRegisterName sets the "register_name" field.
func (oc *OrderCreate) SetRegisterName(s string) *OrderCreate {
	oc.mutation.SetRegisterName(s)
	return oc
}

// SetStorageCondition sets the "storage_condition" field.
func (oc *OrderCreate) SetStorageCondition(s string) *OrderCreate {
	oc.mutation.SetStorageCondition(s)
	return oc
}

// SetCreatedAt sets the "createdAt" field.
func (oc *OrderCreate) SetCreatedAt(t time.Time) *OrderCreate {
	oc.mutation.SetCreatedAt(t)
	return oc
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (oc *OrderCreate) SetNillableCreatedAt(t *time.Time) *OrderCreate {
	if t != nil {
		oc.SetCreatedAt(*t)
	}
	return oc
}

// SetUpdatedAt sets the "updatedAt" field.
func (oc *OrderCreate) SetUpdatedAt(t time.Time) *OrderCreate {
	oc.mutation.SetUpdatedAt(t)
	return oc
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (oc *OrderCreate) SetNillableUpdatedAt(t *time.Time) *OrderCreate {
	if t != nil {
		oc.SetUpdatedAt(*t)
	}
	return oc
}

// SetManagerID sets the "manager" edge to the Account entity by ID.
func (oc *OrderCreate) SetManagerID(id string) *OrderCreate {
	oc.mutation.SetManagerID(id)
	return oc
}

// SetManager sets the "manager" edge to the Account entity.
func (oc *OrderCreate) SetManager(a *Account) *OrderCreate {
	return oc.SetManagerID(a.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (oc *OrderCreate) Mutation() *OrderMutation {
	return oc.mutation
}

// Save creates the Order in the database.
func (oc *OrderCreate) Save(ctx context.Context) (*Order, error) {
	var (
		err  error
		node *Order
	)
	oc.defaults()
	if len(oc.hooks) == 0 {
		if err = oc.check(); err != nil {
			return nil, err
		}
		node, err = oc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OrderMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = oc.check(); err != nil {
				return nil, err
			}
			oc.mutation = mutation
			if node, err = oc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(oc.hooks) - 1; i >= 0; i-- {
			if oc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = oc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, oc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (oc *OrderCreate) SaveX(ctx context.Context) *Order {
	v, err := oc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oc *OrderCreate) Exec(ctx context.Context) error {
	_, err := oc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oc *OrderCreate) ExecX(ctx context.Context) {
	if err := oc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (oc *OrderCreate) defaults() {
	if _, ok := oc.mutation.Oid(); !ok {
		v := order.DefaultOid()
		oc.mutation.SetOid(v)
	}
	if _, ok := oc.mutation.CreatedAt(); !ok {
		v := order.DefaultCreatedAt()
		oc.mutation.SetCreatedAt(v)
	}
	if _, ok := oc.mutation.UpdatedAt(); !ok {
		v := order.DefaultUpdatedAt()
		oc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oc *OrderCreate) check() error {
	if _, ok := oc.mutation.Oid(); !ok {
		return &ValidationError{Name: "oid", err: errors.New(`ent: missing required field "Order.oid"`)}
	}
	if _, ok := oc.mutation.Orderer(); !ok {
		return &ValidationError{Name: "orderer", err: errors.New(`ent: missing required field "Order.orderer"`)}
	}
	if v, ok := oc.mutation.Orderer(); ok {
		if err := order.OrdererValidator(v); err != nil {
			return &ValidationError{Name: "orderer", err: fmt.Errorf(`ent: validator failed for field "Order.orderer": %w`, err)}
		}
	}
	if _, ok := oc.mutation.Receiver(); !ok {
		return &ValidationError{Name: "receiver", err: errors.New(`ent: missing required field "Order.receiver"`)}
	}
	if v, ok := oc.mutation.Receiver(); ok {
		if err := order.ReceiverValidator(v); err != nil {
			return &ValidationError{Name: "receiver", err: fmt.Errorf(`ent: validator failed for field "Order.receiver": %w`, err)}
		}
	}
	if _, ok := oc.mutation.DrugName(); !ok {
		return &ValidationError{Name: "drug_name", err: errors.New(`ent: missing required field "Order.drug_name"`)}
	}
	if v, ok := oc.mutation.DrugName(); ok {
		if err := order.DrugNameValidator(v); err != nil {
			return &ValidationError{Name: "drug_name", err: fmt.Errorf(`ent: validator failed for field "Order.drug_name": %w`, err)}
		}
	}
	if _, ok := oc.mutation.DrugStandard(); !ok {
		return &ValidationError{Name: "drug_standard", err: errors.New(`ent: missing required field "Order.drug_standard"`)}
	}
	if v, ok := oc.mutation.DrugStandard(); ok {
		if err := order.DrugStandardValidator(v); err != nil {
			return &ValidationError{Name: "drug_standard", err: fmt.Errorf(`ent: validator failed for field "Order.drug_standard": %w`, err)}
		}
	}
	if _, ok := oc.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "Order.quantity"`)}
	}
	if _, ok := oc.mutation.RegisterName(); !ok {
		return &ValidationError{Name: "register_name", err: errors.New(`ent: missing required field "Order.register_name"`)}
	}
	if _, ok := oc.mutation.StorageCondition(); !ok {
		return &ValidationError{Name: "storage_condition", err: errors.New(`ent: missing required field "Order.storage_condition"`)}
	}
	if v, ok := oc.mutation.StorageCondition(); ok {
		if err := order.StorageConditionValidator(v); err != nil {
			return &ValidationError{Name: "storage_condition", err: fmt.Errorf(`ent: validator failed for field "Order.storage_condition": %w`, err)}
		}
	}
	if _, ok := oc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "Order.createdAt"`)}
	}
	if _, ok := oc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "Order.updatedAt"`)}
	}
	if _, ok := oc.mutation.ManagerID(); !ok {
		return &ValidationError{Name: "manager", err: errors.New(`ent: missing required edge "Order.manager"`)}
	}
	return nil
}

func (oc *OrderCreate) sqlSave(ctx context.Context) (*Order, error) {
	_node, _spec := oc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (oc *OrderCreate) createSpec() (*Order, *sqlgraph.CreateSpec) {
	var (
		_node = &Order{config: oc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: order.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: order.FieldID,
			},
		}
	)
	if value, ok := oc.mutation.Oid(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: order.FieldOid,
		})
		_node.Oid = value
	}
	if value, ok := oc.mutation.Orderer(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: order.FieldOrderer,
		})
		_node.Orderer = value
	}
	if value, ok := oc.mutation.Receiver(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: order.FieldReceiver,
		})
		_node.Receiver = value
	}
	if value, ok := oc.mutation.DrugName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: order.FieldDrugName,
		})
		_node.DrugName = value
	}
	if value, ok := oc.mutation.DrugStandard(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: order.FieldDrugStandard,
		})
		_node.DrugStandard = value
	}
	if value, ok := oc.mutation.Quantity(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: order.FieldQuantity,
		})
		_node.Quantity = value
	}
	if value, ok := oc.mutation.RegisterName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: order.FieldRegisterName,
		})
		_node.RegisterName = value
	}
	if value, ok := oc.mutation.StorageCondition(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: order.FieldStorageCondition,
		})
		_node.StorageCondition = value
	}
	if value, ok := oc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: order.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := oc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: order.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if nodes := oc.mutation.ManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ManagerTable,
			Columns: []string{order.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: account.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.account_orders = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrderCreateBulk is the builder for creating many Order entities in bulk.
type OrderCreateBulk struct {
	config
	builders []*OrderCreate
}

// Save creates the Order entities in the database.
func (ocb *OrderCreateBulk) Save(ctx context.Context) ([]*Order, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ocb.builders))
	nodes := make([]*Order, len(ocb.builders))
	mutators := make([]Mutator, len(ocb.builders))
	for i := range ocb.builders {
		func(i int, root context.Context) {
			builder := ocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ocb *OrderCreateBulk) SaveX(ctx context.Context) []*Order {
	v, err := ocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ocb *OrderCreateBulk) Exec(ctx context.Context) error {
	_, err := ocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocb *OrderCreateBulk) ExecX(ctx context.Context) {
	if err := ocb.Exec(ctx); err != nil {
		panic(err)
	}
}
